### ISSUE TITLE
javax.inject not found

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anne/google-gin#118]
```
using gin trunk, I'm getting following error:

14:40:02.441 [ERROR] [client] Generator 
'com.google.gwt.inject.rebind.GinjectorGenerator' threw threw an exception 
while rebinding 'org.ires.gwt.client.gin.ClientGinjector'
com.google.inject.internal.ComputationException: 
java.lang.NoClassDefFoundError: javax/inject/Provider
    at com.google.inject.internal.MapMaker$StrategyImpl.compute(MapMaker.java:553)
    at com.google.inject.internal.MapMaker$StrategyImpl.compute(MapMaker.java:419)
    at com.google.inject.internal.CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
    at com.google.inject.internal.FailableCache.get(FailableCache.java:46)
    at com.google.inject.ConstructorInjectorStore.get(ConstructorInjectorStore.java:52)
    at com.google.inject.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:57)
    at com.google.inject.InjectorImpl.initializeBinding(InjectorImpl.java:377)
    at com.google.inject.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:645)
    at com.google.inject.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:581)
    at com.google.inject.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:172)
    at com.google.inject.InjectorImpl.getBindingOrThrow(InjectorImpl.java:132)
    at com.google.inject.InjectorImpl.getInternalFactory(InjectorImpl.java:651)
    at com.google.inject.FactoryProxy.notify(FactoryProxy.java:48)
    at com.google.inject.BindingProcessor.runCreationListeners(BindingProcessor.java:230)
    at com.google.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:131)
    at com.google.inject.InjectorBuilder.build(InjectorBuilder.java:105)
    at com.google.inject.Guice.createInjector(Guice.java:92)
    at com.google.inject.Guice.createInjector(Guice.java:80)
    at com.google.gwt.inject.rebind.GinjectorGenerator.generate(GinjectorGenerator.java:47)
    at com.google.gwt.dev.javac.StandardGeneratorContext.runGenerator(StandardGeneratorContext.java:418)
    at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:38)
    at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.tryRebind(StandardRebindOracle.java:108)
    at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:54)
    at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:154)
    at com.google.gwt.dev.shell.ShellModuleSpaceHost.rebind(ShellModuleSpaceHost.java:119)
    at com.google.gwt.dev.shell.ModuleSpace.rebind(ModuleSpace.java:531)
    at com.google.gwt.dev.shell.ModuleSpace.rebindAndCreate(ModuleSpace.java:414)
    at com.google.gwt.dev.shell.GWTBridgeImpl.create(GWTBridgeImpl.java:39)
    at com.google.gwt.core.client.GWT.create(GWT.java:98)
    at org.ires.gwt.client.Client.<init>(Client.java:13)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at com.google.gwt.dev.shell.ModuleSpace.rebindAndCreate(ModuleSpace.java:422)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:361)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:185)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:380)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:222)
    at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.NoClassDefFoundError: javax/inject/Provider
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2389)
    at java.lang.Class.getDeclaredConstructors(Class.java:1836)
    at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:185)
    at com.google.inject.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:61)
    at com.google.inject.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:31)
    at com.google.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:39)
    at com.google.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:35)
    at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:35)
    at com.google.inject.internal.MapMaker$StrategyImpl.compute(MapMaker.java:549)
    at com.google.inject.internal.MapMaker$StrategyImpl.compute(MapMaker.java:419)
    at com.google.inject.internal.CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
    at com.google.inject.internal.FailableCache.get(FailableCache.java:46)
    at com.google.inject.ConstructorInjectorStore.get(ConstructorInjectorStore.java:52)
    at com.google.inject.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:57)
    at com.google.inject.InjectorImpl.initializeBinding(InjectorImpl.java:377)
    at com.google.inject.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:645)
    at com.google.inject.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:581)
    at com.google.inject.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:172)
    at com.google.inject.InjectorImpl.getBindingOrThrow(InjectorImpl.java:132)
    at com.google.inject.InjectorImpl.getInternalFactory(InjectorImpl.java:651)
    at com.google.inject.FactoryProxy.notify(FactoryProxy.java:48)
    at com.google.inject.BindingProcessor.runCreationListeners(BindingProcessor.java:230)
    at com.google.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:131)
    at com.google.inject.InjectorBuilder.build(InjectorBuilder.java:105)
    at com.google.inject.Guice.createInjector(Guice.java:92)
    at com.google.inject.Guice.createInjector(Guice.java:80)
    at com.google.gwt.inject.rebind.GinjectorGenerator.generate(GinjectorGenerator.java:47)
    at com.google.gwt.dev.javac.StandardGeneratorContext.runGenerator(StandardGeneratorContext.java:418)
    at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:38)
    at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.tryRebind(StandardRebindOracle.java:108)
    at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:54)
    at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:154)
    at com.google.gwt.dev.shell.ShellModuleSpaceHost.rebind(ShellModuleSpaceHost.java:119)
    at com.google.gwt.dev.shell.ModuleSpace.rebind(ModuleSpace.java:531)
    at com.google.gwt.dev.shell.ModuleSpace.rebindAndCreate(ModuleSpace.java:414)
    at com.google.gwt.dev.shell.GWTBridgeImpl.create(GWTBridgeImpl.java:39)
    at com.google.gwt.core.client.GWT.create(GWT.java:98)
    at org.ires.gwt.client.Client.<init>(Client.java:13)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at com.google.gwt.dev.shell.ModuleSpace.rebindAndCreate(ModuleSpace.java:422)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:361)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:185)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:380)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:222)
    at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.ClassNotFoundException: javax.inject.Provider
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2389)
    at java.lang.Class.getDeclaredConstructors(Class.java:1836)
    at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:185)
    at com.google.inject.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:61)
    at com.google.inject.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:31)
    at com.google.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:39)
    at com.google.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:35)
    at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:35)
    at com.google.inject.internal.MapMaker$StrategyImpl.compute(MapMaker.java:549)
    at com.google.inject.internal.MapMaker$StrategyImpl.compute(MapMaker.java:419)
    at com.google.inject.internal.CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
    at com.google.inject.internal.FailableCache.get(FailableCache.java:46)
    at com.google.inject.ConstructorInjectorStore.get(ConstructorInjectorStore.java:52)
    at com.google.inject.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:57)
    at com.google.inject.InjectorImpl.initializeBinding(InjectorImpl.java:377)
    at com.google.inject.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:645)
    at com.google.inject.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:581)
    at com.google.inject.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:172)
    at com.google.inject.InjectorImpl.getBindingOrThrow(InjectorImpl.java:132)
    at com.google.inject.InjectorImpl.getInternalFactory(InjectorImpl.java:651)
    at com.google.inject.FactoryProxy.notify(FactoryProxy.java:48)
    at com.google.inject.BindingProcessor.runCreationListeners(BindingProcessor.java:230)
    at com.google.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:131)
    at com.google.inject.InjectorBuilder.build(InjectorBuilder.java:105)
    at com.google.inject.Guice.createInjector(Guice.java:92)
    at com.google.inject.Guice.createInjector(Guice.java:80)
    at com.google.gwt.inject.rebind.GinjectorGenerator.generate(GinjectorGenerator.java:47)
    at com.google.gwt.dev.javac.StandardGeneratorContext.runGenerator(StandardGeneratorContext.java:418)
    at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:38)
    at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.tryRebind(StandardRebindOracle.java:108)
    at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:54)
    at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:154)
    at com.google.gwt.dev.shell.ShellModuleSpaceHost.rebind(ShellModuleSpaceHost.java:119)
    at com.google.gwt.dev.shell.ModuleSpace.rebind(ModuleSpace.java:531)
    at com.google.gwt.dev.shell.ModuleSpace.rebindAndCreate(ModuleSpace.java:414)
    at com.google.gwt.dev.shell.GWTBridgeImpl.create(GWTBridgeImpl.java:39)
    at com.google.gwt.core.client.GWT.create(GWT.java:98)
    at org.ires.gwt.client.Client.<init>(Client.java:13)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at com.google.gwt.dev.shell.ModuleSpace.rebindAndCreate(ModuleSpace.java:422)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:361)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:185)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:380)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:222)
    at java.lang.Thread.run(Thread.java:619)
```

Original issue reported on code.google.com by `dusan.ma...@gmail.com` on 10 Oct 2010 at 12:52

**Comment by GoogleCodeExporter** [comment]
```
my fault, missing JARs, please invalidate
```

Original comment by `dusan.ma...@gmail.com` on 10 Oct 2010 at 1:05

**Comment by GoogleCodeExporter** [comment]
```
No problem. :)
```

Original comment by `aragos` on 11 Oct 2010 at 5:09
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
Which JARs were you missing? I encountered the same exception, but I'm using 
Maven, all JARs are there.

Thanks.
```

Original comment by `delight....@gmail.com` on 18 Mar 2011 at 9:23

**Comment by GoogleCodeExporter** [comment]
```
I missed javax.inject.jar, which is part of gin release I believe
```

Original comment by `dusan.ma...@gmail.com` on 18 Mar 2011 at 10:55
