### ISSUE TITLE
Breaking changes in GWT svn 9401

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anne/google-gin#131]
```
I tried to build my project with Gin and gwt svn 9401. It fails miserably with 
this message:
run.gwt.compiler.client:
     [java] Compiling module com.noveideje.dostava.App
     [java]    Scanning for additional dependencies: file:/data/user/stole/Development/idea/dostava/trunk/dostavaGwt/client/src/com/noveideje/dostava/gwt/client/MainGinjector.java
     [java]       Computing all possible rebind results for 'com.noveideje.dostava.gwt.client.MainGinjector'
     [java]          Rebinding com.noveideje.dostava.gwt.client.MainGinjector
     [java]             Invoking generator com.google.gwt.inject.rebind.GinjectorGenerator
     [java]                [ERROR] Generator 'com.google.gwt.inject.rebind.GinjectorGenerator' threw an exception while rebinding 'com.noveideje.dostava.gwt.client.MainGinjector'
     [java] com.google.inject.ProvisionException: Guice provision errors:
     [java] 
     [java] 1) Failed to get annotations from public abstract com.noveideje.dostava.gwt.client.activity.ViewDisplay getGlavniDisplay()
     [java] 
     [java] 1 error
     [java]     at com.google.gwt.inject.rebind.util.KeyUtil.getAnnotations(KeyUtil.java:491)
     [java]     at com.google.gwt.inject.rebind.util.KeyUtil.getKey(KeyUtil.java:78)
     [java]     at com.google.gwt.inject.rebind.BindingsProcessor.addUnresolvedEntriesForInjectorInterface(BindingsProcessor.java:387)
     [java]     at com.google.gwt.inject.rebind.BindingsProcessor.process(BindingsProcessor.java:234)
     [java]     at com.google.gwt.inject.rebind.GinjectorGeneratorImpl.generate(GinjectorGeneratorImpl.java:76)
     [java]     at com.google.gwt.inject.rebind.GinjectorGenerator.generate(GinjectorGenerator.java:47)
     [java]     at com.google.gwt.dev.javac.StandardGeneratorContext.runGenerator(StandardGeneratorContext.java:427)
     [java]     at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:39)
     [java]     at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.tryRebind(StandardRebindOracle.java:115)
     [java]     at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:58)
     [java]     at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:161)
     [java]     at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:150)
     [java]     at com.google.gwt.dev.DistillerRebindPermutationOracle.getAllPossibleRebindAnswers(DistillerRebindPermutationOracle.java:91)
     [java]     at com.google.gwt.dev.jdt.WebModeCompilerFrontEnd.doFindAdditionalTypesUsingRebinds(WebModeCompilerFrontEnd.java:106)
     [java]     at com.google.gwt.dev.jdt.AbstractCompiler$Sandbox$CompilerImpl.process(AbstractCompiler.java:254)
     [java]     at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:444)
     [java]     at com.google.gwt.dev.jdt.AbstractCompiler$Sandbox$CompilerImpl.compile(AbstractCompiler.java:175)
     [java]     at com.google.gwt.dev.jdt.AbstractCompiler$Sandbox$CompilerImpl.compile(AbstractCompiler.java:288)
     [java]     at com.google.gwt.dev.jdt.AbstractCompiler$Sandbox$CompilerImpl.access$400(AbstractCompiler.java:145)
     [java]     at com.google.gwt.dev.jdt.AbstractCompiler.compile(AbstractCompiler.java:632)
     [java]     at com.google.gwt.dev.jdt.BasicWebModeCompiler.getCompilationUnitDeclarations(BasicWebModeCompiler.java:124)
     [java]     at com.google.gwt.dev.jdt.WebModeCompilerFrontEnd.getCompilationUnitDeclarations(WebModeCompilerFrontEnd.java:54)
     [java]     at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:517)
     [java]     at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:35)
     [java]     at com.google.gwt.dev.Precompile.precompile(Precompile.java:533)
     [java]     at com.google.gwt.dev.Precompile.precompile(Precompile.java:487)
     [java]     at com.google.gwt.dev.Precompile.precompile(Precompile.java:399)
     [java]     at com.google.gwt.dev.Compiler.run(Compiler.java:215)
     [java]     at com.google.gwt.dev.Compiler.run(Compiler.java:187)
     [java]     at com.google.gwt.dev.Compiler$1.run(Compiler.java:159)
     [java]     at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:87)
     [java]     at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:81)
     [java]     at com.google.gwt.dev.Compiler.main(Compiler.java:166)
     [java] Caused by: java.lang.NoSuchMethodException: com.google.gwt.core.ext.typeinfo.JAbstractMethod.getAnnotations()
     [java]     at java.lang.Class.getDeclaredMethod(Class.java:1954)
     [java]     at com.google.gwt.inject.rebind.util.KeyUtil.getAnnotations(KeyUtil.java:487)
     [java]     ... 32 more

It would seem that they have removed the method 
com.google.gwt.core.ext.typeinfo.JAbstractMethod.getAnnotations()

Anybody else run into this?
```

Original issue reported on code.google.com by `dilbert....@gmail.com` on 11 Dec 2010 at 3:07

**Comment by GoogleCodeExporter** [comment]
```
This is a known issue, we already have a patch but I still have to apply it. 
Should be fixed shortly!
```

Original comment by `aragos` on 11 Dec 2010 at 4:17
- Changed state: **Accepted**
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the quick response. I'd like the patch to be available as soon as 
possible. Thanks again.
```

Original comment by `dilbert....@gmail.com` on 11 Dec 2010 at 5:02

**Comment by GoogleCodeExporter** [comment]
```
Submitted patch at r155. Note that this change makes Gin backwards-incompatible 
- I'll do a better internal cleanup soon that will remove this dependency and 
make Gin compatible with more GWT versions again.
```

Original comment by `aragos` on 12 Dec 2010 at 10:02

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the quick response. I tried to build the app but now it fails in the 
gwt-maps module so I can not confirm that everything is OK. If I find another 
problem I'll let You know.
```

Original comment by `dilbert....@gmail.com` on 13 Dec 2010 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
Yes, the recent GWT internals change (r9400) caused binary incompatibilities 
with several GWT-related projects. Recompiling those jars against the new GWT 
version should help.
```

Original comment by `aragos` on 13 Dec 2010 at 5:35

**Comment by GoogleCodeExporter** [comment]
```
As of r159, Gin is once again compatible with GWT 2.1.1 and earlier and HEAD.
```

Original comment by `aragos` on 21 Jan 2011 at 9:17

**Comment by GoogleCodeExporter** [comment]
Original comment by `aragos` on 21 Jan 2011 at 9:17
- Changed state: **Fixed**
