### ISSUE TITLE
Class visibility forced to be public

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anne/google-gin#148]
```
What steps will reproduce the problem?
1. Use and @Inject on a class which isn't public (but friendly)

What is the expected output? What do you see instead?
The compilation should work. It worked in the gin-1.0 version. I have the 
following issue:

 [java] Compiling module com.freemymove.ufe.UserFrontEnd
     [java]    Scanning for additional dependencies: file:/C:/wamp/www/Unswitch/dev/ufe/src/com/freemymove/ufe/client/UserFrontEnd.java
     [java]       Computing all possible rebind results for 'com.freemymove.ufe.client.UserFrontEndGinjector'
     [java]          Rebinding com.freemymove.ufe.client.UserFrontEndGinjector
     [java]             Invoking generator com.google.gwt.inject.rebind.GinjectorGenerator
     [java]                [ERROR] Generator 'com.google.gwt.inject.rebind.GinjectorGenerator' threw an exception while rebinding 'com.freemymove.ufe.client.UserFrontEndGinjector'
     [java] java.lang.NullPointerException
     [java]     at com.google.gwt.inject.rebind.util.SourceWriteUtil.getBinaryName(SourceWriteUtil.java:530)
     [java]     at com.google.gwt.inject.rebind.util.SourceWriteUtil.getJniSignature(SourceWriteUtil.java:497)
     [java]     at com.google.gwt.inject.rebind.util.SourceWriteUtil.getJsniSignature(SourceWriteUtil.java:467)
     [java]     at com.google.gwt.inject.rebind.util.SourceWriteUtil.createMethodCallWithInjection(SourceWriteUtil.java:312)
     [java]     at com.google.gwt.inject.rebind.util.SourceWriteUtil.createMethodCallWithInjection(SourceWriteUtil.java:213)
     [java]     at com.google.gwt.inject.rebind.util.SourceWriteUtil.createConstructorInjection(SourceWriteUtil.java:191)
     [java]     at com.google.gwt.inject.rebind.binding.CallConstructorBinding.appendCreationStatement(CallConstructorBinding.java:54)
     [java]     at com.google.gwt.inject.rebind.binding.CreatorBinding.writeCreatorMethods(CreatorBinding.java:66)
     [java]     at com.google.gwt.inject.rebind.GinjectorOutputter.outputBinding(GinjectorOutputter.java:210)
     [java]     at com.google.gwt.inject.rebind.GinjectorOutputter.outputBindings(GinjectorOutputter.java:187)
     [java]     at com.google.gwt.inject.rebind.GinjectorOutputter.output(GinjectorOutputter.java:143)
     [java]     at com.google.gwt.inject.rebind.GinjectorGeneratorImpl.generate(GinjectorGeneratorImpl.java:73)
     [java]     at com.google.gwt.inject.rebind.GinjectorGenerator.generate(GinjectorGenerator.java:66)


What version of the product are you using? On what operating system?
gin-head and GWT-2.2.0

Please provide any additional information below.


```

Original issue reported on code.google.com by `cdebuss...@gmail.com` on 5 Apr 2011 at 4:05

**Comment by GoogleCodeExporter** [comment]
```
I'm actually working on this very issue right now, for some reason the new 
class loader has trouble picking up some packages. Gin HEAD is a bit unstable 
now so please bear with me as I track down and fix a bunch of errors like this.
```

Original comment by `aragos` on 5 Apr 2011 at 4:11
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Issue 147 has been merged into this issue.
```

Original comment by `aragos` on 5 Apr 2011 at 4:12

**Comment by GoogleCodeExporter** [comment]
```
Fixed in r194.
```

Original comment by `aragos` on 5 Apr 2011 at 7:01
- Changed state: **Fixed**
